using System.Collections.ObjectModel;
using System.Text.RegularExpressions;
using System.Windows.Input;
using OracleEntityGenerator.CodeGeneration;
using OracleEntityGenerator.Core.Generation;
using OracleEntityGenerator.Core.Naming;
using Oracle.ManagedDataAccess.Client;
using OracleEntityGenerator.Oracle;
using OracleEntityGenerator.VsExtension.Commands;
using OracleEntityGenerator.VsExtension.Services;
using OracleEntityGenerator.VsExtension.Settings;

namespace OracleEntityGenerator.VsExtension.ViewModels;

public sealed class GeneratorToolWindowViewModel : ObservableObject
{
    private readonly IOracleMetadataReader _metadataReader;
    private readonly OracleCodeGenerationService _codeGenerationService;
    private readonly GeneratedFileWriter _fileWriter;
    private readonly GeneratorSettingsStore _settingsStore;
    private string _host = string.Empty;
    private int _port = 1521;
    private string _serviceName = string.Empty;
    private string _userName = string.Empty;
    private string _password = string.Empty;
    private string _fullConnectionString = string.Empty;
    private string? _selectedSchemaName;
    private string _entityNamespace = "MyProject.Domain.Entities";
    private string _configurationNamespace = "MyProject.Infrastructure.Persistence.Configurations";
    private string _outputDirectory = string.Empty;
    private string _entityOutputDirectory = "Entities";
    private string _configurationOutputDirectory = "Configurations";
    private string _tablePrefixesToRemove = string.Empty;
    private string _columnPrefixesToRemove = string.Empty;
    private string _tableSearchText = string.Empty;
    private string _logText = string.Empty;
    private bool _showSystemSchemas;
    private bool _overwriteExistingFiles;
    private bool _nullableReferenceTypes = true;
    private bool _generateXmlComments;
    private bool _generateKeylessEntities;
    private bool _isBusy;
    private bool _isSynchronizingConnectionFields;
    private string _fileHeader = "// <auto-generated />\n// Generated by Oracle Entity Generator.";
    private string _entityUsings = string.Empty;
    private string _configurationUsings = string.Empty;

    public GeneratorToolWindowViewModel()
        : this(
            new OracleMetadataReader(),
            new OracleCodeGenerationService(),
            new GeneratedFileWriter(),
            new GeneratorSettingsStore())
    {
    }

    public GeneratorToolWindowViewModel(
        IOracleMetadataReader metadataReader,
        OracleCodeGenerationService codeGenerationService,
        GeneratedFileWriter fileWriter,
        GeneratorSettingsStore settingsStore)
    {
        _metadataReader = metadataReader;
        _codeGenerationService = codeGenerationService;
        _fileWriter = fileWriter;
        _settingsStore = settingsStore;

        TestConnectionCommand = new AsyncRelayCommand(TestConnectionAsync, CanConnect);
        LoadSchemasCommand = new AsyncRelayCommand(LoadSchemasAsync, CanConnect);
        LoadTablesCommand = new AsyncRelayCommand(LoadTablesAsync, () => !string.IsNullOrWhiteSpace(SelectedSchemaName));
        GenerateCommand = new AsyncRelayCommand(GenerateAsync, CanGenerate);
        SaveSettingsCommand = new AsyncRelayCommand(SaveSettingsAsync);
        LoadSettingsCommand = new AsyncRelayCommand(LoadSettingsAsync);
    }

    public ObservableCollection<string> Schemas { get; } = [];

    public ObservableCollection<TableSelectionViewModel> Tables { get; } = [];

    public ICommand TestConnectionCommand { get; }

    public ICommand LoadSchemasCommand { get; }

    public ICommand LoadTablesCommand { get; }

    public ICommand GenerateCommand { get; }

    public ICommand SaveSettingsCommand { get; }

    public ICommand LoadSettingsCommand { get; }

    public string Host
    {
        get => _host;
        set
        {
            if (SetAndRefreshCommands(ref _host, value))
            {
                UpdateFullConnectionStringFromFields();
            }
        }
    }

    public int Port
    {
        get => _port;
        set
        {
            if (SetAndRefreshCommands(ref _port, value))
            {
                UpdateFullConnectionStringFromFields();
            }
        }
    }

    public string ServiceName
    {
        get => _serviceName;
        set
        {
            if (SetAndRefreshCommands(ref _serviceName, value))
            {
                UpdateFullConnectionStringFromFields();
            }
        }
    }

    public string UserName
    {
        get => _userName;
        set
        {
            if (SetAndRefreshCommands(ref _userName, value))
            {
                UpdateFullConnectionStringFromFields();
            }
        }
    }

    public string Password
    {
        get => _password;
        set
        {
            if (SetAndRefreshCommands(ref _password, value))
            {
                UpdateFullConnectionStringFromFields();
            }
        }
    }

    public string FullConnectionString
    {
        get => _fullConnectionString;
        set => SetAndRefreshCommands(ref _fullConnectionString, value);
    }

    public string? SelectedSchemaName { get => _selectedSchemaName; set => SetAndRefreshCommands(ref _selectedSchemaName, value); }

    public string EntityNamespace { get => _entityNamespace; set => SetAndRefreshCommands(ref _entityNamespace, value); }

    public string ConfigurationNamespace { get => _configurationNamespace; set => SetAndRefreshCommands(ref _configurationNamespace, value); }

    public string OutputDirectory { get => _outputDirectory; set => SetAndRefreshCommands(ref _outputDirectory, value); }

    public string EntityOutputDirectory { get => _entityOutputDirectory; set => SetProperty(ref _entityOutputDirectory, value); }

    public string ConfigurationOutputDirectory { get => _configurationOutputDirectory; set => SetProperty(ref _configurationOutputDirectory, value); }

    public string TablePrefixesToRemove { get => _tablePrefixesToRemove; set => SetProperty(ref _tablePrefixesToRemove, value); }

    public string ColumnPrefixesToRemove { get => _columnPrefixesToRemove; set => SetProperty(ref _columnPrefixesToRemove, value); }

    public string TableSearchText
    {
        get => _tableSearchText;
        set
        {
            if (SetProperty(ref _tableSearchText, value))
            {
                OnPropertyChanged(nameof(VisibleTables));
            }
        }
    }

    public IEnumerable<TableSelectionViewModel> VisibleTables
    {
        get
        {
            if (string.IsNullOrWhiteSpace(TableSearchText))
            {
                return Tables;
            }

            return Tables.Where(x => x.TableName.Contains(TableSearchText, StringComparison.OrdinalIgnoreCase)
                || x.SchemaName.Contains(TableSearchText, StringComparison.OrdinalIgnoreCase)
                || (x.Comment?.Contains(TableSearchText, StringComparison.OrdinalIgnoreCase) ?? false));
        }
    }

    public string LogText { get => _logText; set => SetProperty(ref _logText, value); }

    public bool ShowSystemSchemas { get => _showSystemSchemas; set => SetProperty(ref _showSystemSchemas, value); }

    public bool OverwriteExistingFiles { get => _overwriteExistingFiles; set => SetProperty(ref _overwriteExistingFiles, value); }

    public bool NullableReferenceTypes { get => _nullableReferenceTypes; set => SetProperty(ref _nullableReferenceTypes, value); }

    public bool GenerateXmlComments { get => _generateXmlComments; set => SetProperty(ref _generateXmlComments, value); }

    public bool GenerateKeylessEntities { get => _generateKeylessEntities; set => SetProperty(ref _generateKeylessEntities, value); }

    public bool IsBusy { get => _isBusy; set => SetAndRefreshCommands(ref _isBusy, value); }

    public string FileHeader { get => _fileHeader; set => SetProperty(ref _fileHeader, value); }

    public string EntityUsings { get => _entityUsings; set => SetProperty(ref _entityUsings, value); }

    public string ConfigurationUsings { get => _configurationUsings; set => SetProperty(ref _configurationUsings, value); }

    private async Task TestConnectionAsync(CancellationToken cancellationToken)
    {
        await RunBusyAsync(async () =>
        {
            await _metadataReader.TestConnectionAsync(CreateConnectionOptions(), cancellationToken);
            var synchronized = UpdateConnectionFieldsFromSuccessfulConnectionString();
            if (synchronized)
            {
                AppendLog($"Connection fields updated from connection string: {Host}:{Port}/{ServiceName}, user {UserName}.");
            }
            else if (!string.IsNullOrWhiteSpace(FullConnectionString))
            {
                AppendLog("Connection succeeded, but the connection string data source could not be split into host, port, and service fields.");
            }

            AppendLog("Connection succeeded.");
        });
    }

    private async Task LoadSchemasAsync(CancellationToken cancellationToken)
    {
        await RunBusyAsync(async () =>
        {
            Schemas.Clear();
            Tables.Clear();

            var schemas = await _metadataReader.GetAccessibleSchemasAsync(
                CreateConnectionOptions(),
                CreateReaderOptions(),
                cancellationToken);

            foreach (var schema in schemas)
            {
                Schemas.Add(schema.SchemaName);
            }

            SelectedSchemaName = Schemas.FirstOrDefault();
            AppendLog($"Loaded {Schemas.Count} accessible schema(s).");
        });
    }

    private async Task LoadTablesAsync(CancellationToken cancellationToken)
    {
        var selectedSchemaName = SelectedSchemaName;
        if (selectedSchemaName is null || selectedSchemaName.Trim().Length == 0)
        {
            return;
        }

        await RunBusyAsync(async () =>
        {
            Tables.Clear();
            var tables = await _metadataReader.GetTablesAsync(
                CreateConnectionOptions(),
                selectedSchemaName,
                CreateReaderOptions(),
                cancellationToken);

            foreach (var table in tables)
            {
                Tables.Add(new TableSelectionViewModel(table));
            }

            OnPropertyChanged(nameof(VisibleTables));
            AppendLog($"Loaded {Tables.Count} table(s) from schema {selectedSchemaName}.");
        });
    }

    private async Task GenerateAsync(CancellationToken cancellationToken)
    {
        await RunBusyAsync(async () =>
        {
            var selectedTables = Tables.Where(x => x.IsSelected).ToArray();
            if (selectedTables.Length == 0)
            {
                AppendLog("No tables selected.");
                return;
            }

            var metadata = new List<Core.Metadata.OracleTableMetadata>();

            foreach (var selectedTable in selectedTables)
            {
                if (!selectedTable.HasPrimaryKey && !GenerateKeylessEntities)
                {
                    AppendLog($"Skipped {selectedTable.SchemaName}.{selectedTable.TableName}: primary key not found.");
                    continue;
                }

                metadata.Add(await _metadataReader.GetTableMetadataAsync(
                    CreateConnectionOptions(),
                    selectedTable.SchemaName,
                    selectedTable.TableName,
                    cancellationToken));
            }

            var files = _codeGenerationService.GenerateFiles(metadata, CreateGenerationOptions());
            await _fileWriter.WriteFilesAsync(OutputDirectory, files, OverwriteExistingFiles, cancellationToken);
            AppendLog($"Generated {files.Count} file(s) for {metadata.Count} table(s).");
        });
    }

    private async Task SaveSettingsAsync(CancellationToken cancellationToken)
    {
        await RunBusyAsync(async () =>
        {
            await _settingsStore.SaveAsync(CreateSettingsProfile(), cancellationToken);
            AppendLog($"Settings saved: {_settingsStore.SettingsFilePath}");
        });
    }

    private async Task LoadSettingsAsync(CancellationToken cancellationToken)
    {
        await RunBusyAsync(async () =>
        {
            var profile = await _settingsStore.LoadAsync(cancellationToken);
            if (profile is null)
            {
                AppendLog("No saved settings profile found.");
                return;
            }

            ApplySettingsProfile(profile);
            AppendLog($"Settings loaded: {_settingsStore.SettingsFilePath}");
        });
    }

    private OracleConnectionOptions CreateConnectionOptions()
    {
        return new OracleConnectionOptions
        {
            FullConnectionString = string.IsNullOrWhiteSpace(FullConnectionString) ? null : FullConnectionString,
            Host = Host,
            Port = Port,
            ServiceName = ServiceName,
            UserName = UserName,
            Password = Password
        };
    }

    private OracleMetadataReaderOptions CreateReaderOptions()
    {
        return new OracleMetadataReaderOptions
        {
            ShowSystemSchemas = ShowSystemSchemas
        };
    }

    private GenerationOptions CreateGenerationOptions()
    {
        return new GenerationOptions
        {
            EntityNamespace = EntityNamespace,
            ConfigurationNamespace = ConfigurationNamespace,
            EntityOutputDirectory = EntityOutputDirectory,
            ConfigurationOutputDirectory = ConfigurationOutputDirectory,
            NullableReferenceTypes = NullableReferenceTypes,
            GenerateXmlComments = GenerateXmlComments,
            OverwriteExistingFiles = OverwriteExistingFiles,
            GenerateKeylessEntities = GenerateKeylessEntities,
            Naming = new NamingOptions
            {
                TablePrefixesToRemove = SplitCsv(TablePrefixesToRemove),
                ColumnPrefixesToRemove = SplitCsv(ColumnPrefixesToRemove)
            },
            Template = new TemplateOptions
            {
                FileHeader = string.IsNullOrWhiteSpace(FileHeader) ? null : FileHeader,
                EntityUsings = SplitCsv(EntityUsings),
                ConfigurationUsings = SplitCsv(ConfigurationUsings)
            }
        };
    }

    private GeneratorSettingsProfile CreateSettingsProfile()
    {
        return new GeneratorSettingsProfile
        {
            Host = Host,
            Port = Port,
            ServiceName = ServiceName,
            UserName = UserName,
            FullConnectionString = FullConnectionString,
            ShowSystemSchemas = ShowSystemSchemas,
            EntityNamespace = EntityNamespace,
            ConfigurationNamespace = ConfigurationNamespace,
            OutputDirectory = OutputDirectory,
            EntityOutputDirectory = EntityOutputDirectory,
            ConfigurationOutputDirectory = ConfigurationOutputDirectory,
            TablePrefixesToRemove = TablePrefixesToRemove,
            ColumnPrefixesToRemove = ColumnPrefixesToRemove,
            OverwriteExistingFiles = OverwriteExistingFiles,
            NullableReferenceTypes = NullableReferenceTypes,
            GenerateXmlComments = GenerateXmlComments,
            GenerateKeylessEntities = GenerateKeylessEntities,
            FileHeader = FileHeader,
            EntityUsings = EntityUsings,
            ConfigurationUsings = ConfigurationUsings
        };
    }

    private void ApplySettingsProfile(GeneratorSettingsProfile profile)
    {
        Host = profile.Host;
        Port = profile.Port;
        ServiceName = profile.ServiceName;
        UserName = profile.UserName;
        FullConnectionString = profile.FullConnectionString;
        ShowSystemSchemas = profile.ShowSystemSchemas;
        EntityNamespace = profile.EntityNamespace;
        ConfigurationNamespace = profile.ConfigurationNamespace;
        OutputDirectory = profile.OutputDirectory;
        EntityOutputDirectory = profile.EntityOutputDirectory;
        ConfigurationOutputDirectory = profile.ConfigurationOutputDirectory;
        TablePrefixesToRemove = profile.TablePrefixesToRemove;
        ColumnPrefixesToRemove = profile.ColumnPrefixesToRemove;
        OverwriteExistingFiles = profile.OverwriteExistingFiles;
        NullableReferenceTypes = profile.NullableReferenceTypes;
        GenerateXmlComments = profile.GenerateXmlComments;
        GenerateKeylessEntities = profile.GenerateKeylessEntities;
        FileHeader = profile.FileHeader;
        EntityUsings = profile.EntityUsings;
        ConfigurationUsings = profile.ConfigurationUsings;
    }

    private bool CanConnect()
    {
        return !IsBusy
            && (!string.IsNullOrWhiteSpace(FullConnectionString)
                || (!string.IsNullOrWhiteSpace(Host)
                    && !string.IsNullOrWhiteSpace(ServiceName)
                    && !string.IsNullOrWhiteSpace(UserName)
                    && !string.IsNullOrWhiteSpace(Password)));
    }

    private bool CanGenerate()
    {
        return !IsBusy
            && !string.IsNullOrWhiteSpace(OutputDirectory)
            && !string.IsNullOrWhiteSpace(EntityNamespace)
            && !string.IsNullOrWhiteSpace(ConfigurationNamespace)
            && Tables.Any(x => x.IsSelected);
    }

    private async Task RunBusyAsync(Func<Task> operation)
    {
        try
        {
            IsBusy = true;
            await operation();
        }
        catch (Exception exception)
        {
            AppendLog(exception.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    private void AppendLog(string message)
    {
        LogText = string.IsNullOrWhiteSpace(LogText)
            ? message
            : $"{LogText}{Environment.NewLine}{message}";
    }

    private bool SetAndRefreshCommands<T>(ref T field, T value)
    {
        if (SetProperty(ref field, value))
        {
            RaiseCommandStatesChanged();
            return true;
        }

        return false;
    }

    private void RaiseCommandStatesChanged()
    {
        ((AsyncRelayCommand)TestConnectionCommand).RaiseCanExecuteChanged();
        ((AsyncRelayCommand)LoadSchemasCommand).RaiseCanExecuteChanged();
        ((AsyncRelayCommand)LoadTablesCommand).RaiseCanExecuteChanged();
        ((AsyncRelayCommand)GenerateCommand).RaiseCanExecuteChanged();
        ((AsyncRelayCommand)SaveSettingsCommand).RaiseCanExecuteChanged();
        ((AsyncRelayCommand)LoadSettingsCommand).RaiseCanExecuteChanged();
    }

    private static IReadOnlyList<string> SplitCsv(string value)
    {
        return value
            .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(x => x.Trim())
            .Where(x => x.Length > 0)
            .ToArray();
    }

    private void UpdateFullConnectionStringFromFields()
    {
        if (_isSynchronizingConnectionFields
            || string.IsNullOrWhiteSpace(Host)
            || string.IsNullOrWhiteSpace(ServiceName))
        {
            return;
        }

        try
        {
            _isSynchronizingConnectionFields = true;

            var builder = new OracleConnectionStringBuilder
            {
                DataSource = $"{Host}:{Port}/{ServiceName}",
                UserID = UserName,
                Password = Password,
                PersistSecurityInfo = false
            };

            FullConnectionString = builder.ConnectionString;
        }
        finally
        {
            _isSynchronizingConnectionFields = false;
        }
    }

    private bool UpdateConnectionFieldsFromConnectionString(string connectionString)
    {
        if (_isSynchronizingConnectionFields || string.IsNullOrWhiteSpace(connectionString))
        {
            return false;
        }

        try
        {
            if (!TryGetConnectionStringValue(connectionString, "Data Source", out var dataSource)
                && !TryGetConnectionStringValue(connectionString, "DataSource", out dataSource))
            {
                dataSource = string.Empty;
            }

            TryGetConnectionStringValue(connectionString, "User Id", out var userId);
            TryGetConnectionStringValue(connectionString, "UserID", out var alternateUserId);
            TryGetConnectionStringValue(connectionString, "Password", out var password);

            if (string.IsNullOrWhiteSpace(userId))
            {
                userId = alternateUserId;
            }

            if (string.IsNullOrWhiteSpace(dataSource)
                || string.IsNullOrWhiteSpace(userId)
                || string.IsNullOrWhiteSpace(password))
            {
                var builder = new OracleConnectionStringBuilder(connectionString);
                dataSource = builder.DataSource;
                userId = builder.UserID;
                password = builder.Password;
            }

            _isSynchronizingConnectionFields = true;

            var parsedDataSource = TryParseEasyConnectDataSource(dataSource, out var host, out var port, out var serviceName)
                || TryParseTnsDescriptorDataSource(dataSource, out host, out port, out serviceName);

            if (parsedDataSource)
            {
                SetProperty(ref _host, host, nameof(Host));
                SetProperty(ref _port, port, nameof(Port));
                SetProperty(ref _serviceName, serviceName, nameof(ServiceName));
            }

            SetProperty(ref _userName, userId, nameof(UserName));
            SetProperty(ref _password, password, nameof(Password));
            RaiseCommandStatesChanged();
            return parsedDataSource;
        }
        catch (ArgumentException)
        {
            // Ignore partial connection strings while the user is still typing.
            return false;
        }
        finally
        {
            _isSynchronizingConnectionFields = false;
        }
    }

    private bool UpdateConnectionFieldsFromSuccessfulConnectionString()
    {
        if (!string.IsNullOrWhiteSpace(FullConnectionString))
        {
            return UpdateConnectionFieldsFromConnectionString(FullConnectionString);
        }

        return false;
    }

    private static bool TryParseEasyConnectDataSource(
        string dataSource,
        out string host,
        out int port,
        out string serviceName)
    {
        host = string.Empty;
        port = 1521;
        serviceName = string.Empty;

        if (string.IsNullOrWhiteSpace(dataSource) || dataSource.StartsWith("(", StringComparison.Ordinal))
        {
            return false;
        }

        var slashIndex = dataSource.IndexOf("/", StringComparison.Ordinal);
        if (slashIndex < 0)
        {
            return false;
        }

        var hostAndPort = dataSource.Substring(0, slashIndex);
        serviceName = dataSource.Substring(slashIndex + 1);

        var colonIndex = hostAndPort.LastIndexOf(':');
        if (colonIndex >= 0)
        {
            host = hostAndPort.Substring(0, colonIndex);
            if (int.TryParse(hostAndPort.Substring(colonIndex + 1), out var parsedPort))
            {
                port = parsedPort;
            }
        }
        else
        {
            host = hostAndPort;
        }

        return !string.IsNullOrWhiteSpace(host) && !string.IsNullOrWhiteSpace(serviceName);
    }

    private static bool TryParseTnsDescriptorDataSource(
        string dataSource,
        out string host,
        out int port,
        out string serviceName)
    {
        host = GetTnsValue(dataSource, "HOST");
        serviceName = GetTnsValue(dataSource, "SERVICE_NAME");
        port = int.TryParse(GetTnsValue(dataSource, "PORT"), out var parsedPort)
            ? parsedPort
            : 1521;

        return !string.IsNullOrWhiteSpace(host) && !string.IsNullOrWhiteSpace(serviceName);
    }

    private static string GetTnsValue(string dataSource, string key)
    {
        var match = Regex.Match(
            dataSource,
            $@"\(\s*{Regex.Escape(key)}\s*=\s*([^)]+)\)",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        return match.Success ? match.Groups[1].Value.Trim() : string.Empty;
    }

    private static bool TryGetConnectionStringValue(
        string connectionString,
        string key,
        out string value)
    {
        value = string.Empty;

        foreach (var segment in connectionString
            .Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(x => x.Trim())
            .Where(x => x.Length > 0))
        {
            var equalsIndex = segment.IndexOf('=');
            if (equalsIndex <= 0)
            {
                continue;
            }

            var segmentKey = segment.Substring(0, equalsIndex).Trim();
            if (!segmentKey.Equals(key, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            value = segment.Substring(equalsIndex + 1).Trim();
            return true;
        }

        return false;
    }
}
